apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: ${namespace}
  labels:
    app: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-${version}
  namespace: ${namespace}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: ${version}
    spec:
      containers:
      - name: reviews
        image: bevyx/demo-bookinfo-reviews:${version}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080